# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - task: build
    silent: true

  build:
    cmds:
      - go build -ldflags="-s -w" main.go
    silent: true

  upx:
    cmds:
      - go build -ldflags="-s -w" -o clipllama main.go && upx clipllama
    silent: true
