# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - task: build
    silent: true

  build:
    cmds:
      - go build -ldflags="-s -w" -o c3l main.go 
    silent: true

  upx:
    cmds:
      - go build -ldflags="-s -w" -o c3l main.go && upx c3l
    silent: true
