# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - task: build
    silent: true

  build:
    cmds:
      - go build -ldflags="-s -w" -o c3l main.go 
    silent: true

  test-release:
    cmds:
      - goreleaser release --snapshot --clean
    silent: true

  prod-release:
    cmds:
      - goreleaser release --clean
    silent: true
